Note page frontend
SPS-Daredevils-SM-21/NoteTakingApp pull request #3
Opened 2021-07-08 05:43 UTC by SauceRSC

Frontend of the note pages (view notes and add a note)

2021-07-08 18:01 UTC, dgalbraith33 requested changes

2021-07-08 18:01 UTC, dgalbraith33 commented on .gitignore
> +.vscode/settings.json
please add the following

```
.classpath
.project
.settings/
```

and then git rm those files so they don't show up in the pr.

2021-07-10 04:12 UTC, SauceRSC commented on .gitignore
> +.vscode/settings.json
Already correct that

2021-07-13 17:47 UTC, dgalbraith33 requested changes

2021-07-13 17:47 UTC, dgalbraith33 commented on .gitignore
> +.vscode/settings.json
You still need to `git rm` those files (they are still in the PR).

2021-07-13 21:29 UTC, dgalbraith33 approved these changes

2021-07-15 05:40 UTC, merged