HTML Page for Login
SPS-Daredevils-SM-21/NoteTakingApp pull request #6
Opened 2021-07-15 19:40 UTC by haseebc2000

Final HTML page for login

2021-07-15 21:25 UTC, dgalbraith33 requested changes

2021-07-15 21:25 UTC, dgalbraith33 commented on src/main/webapp/style.css
> +/*#content {
Instead of commenting out this code, you can delete it.

It will always be in the git history in case we need to get it back :)

2021-07-20 00:23 UTC, tdescartes approved these changes

2021-07-20 00:23 UTC, tdescartes approved these changes

2021-07-20 00:44 UTC, tdescartes approved these changes

2021-07-20 00:46 UTC, tdescartes approved these changes

2021-07-20 00:47 UTC, tdescartes approved these changes

2021-07-20 00:47 UTC, tdescartes approved these changes

2021-07-20 00:48 UTC, merged